A=int(input("Enter the value of A "))
B=int(input("Enter the value of B "))
M=int(input("Enter the value of M "))
C=int(input("Enter the value of C "))
N=int(input("Enter the value of N "))
print((((2*A*B)/5)+25)-(A/(8(C+N))))
